# Generated by Django 6.0.2 on 2026-02-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('team_leader', 'Team Leader'), ('collaborator', 'Collaborator'), ('client', 'Client')], max_length=20),
        ),
    ]
