# Generated by Django 6.0.2 on 2026-02-07 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'team_leader'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_teams', to='workspaces.workspacemember'),
        ),
    ]
